/**
 * Bảng mã lỗi chuẩn toàn hệ thống theo API.md §13 (v1.2.8).
 * Giúp Frontend định danh lỗi dạng máy đọc (machine-readable string).
 */

const ERROR_CODES = {
  // Lỗi xác thực & phân quyền & tài khoản
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  LAST_ACTIVE_ADMIN: 'LAST_ACTIVE_ADMIN',

  // Lỗi tòa nhà, loại phòng, phòng & giường
  ROOM_FULL: 'ROOM_FULL',
  BUILDING_HAS_OCCUPANTS: 'BUILDING_HAS_OCCUPANTS',
  ROOM_TYPE_MISMATCH: 'ROOM_TYPE_MISMATCH',
  ROOM_TYPE_IN_USE: 'ROOM_TYPE_IN_USE',
  ROOM_HAS_OCCUPANTS: 'ROOM_HAS_OCCUPANTS',
  BED_OCCUPIED: 'BED_OCCUPIED',
  GENDER_MISMATCH: 'GENDER_MISMATCH',

  // Lỗi đơn đăng ký, sinh viên, hợp đồng & yêu cầu
  DUPLICATE_PENDING_APPLICATION: 'DUPLICATE_PENDING_APPLICATION',
  APPLICATION_NOT_PENDING: 'APPLICATION_NOT_PENDING',
  STUDENT_HAS_ACTIVE_CONTRACT: 'STUDENT_HAS_ACTIVE_CONTRACT',
  STUDENT_HAS_DEBT: 'STUDENT_HAS_DEBT',
  CONTRACT_NOT_ACTIVE: 'CONTRACT_NOT_ACTIVE',
  DUPLICATE_PENDING_REQUEST: 'DUPLICATE_PENDING_REQUEST',
  REQUEST_NOT_PENDING: 'REQUEST_NOT_PENDING',

  // Lỗi hóa đơn, chỉ số điện nước & thanh toán
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_HAS_PAYMENT: 'INVOICE_HAS_PAYMENT',
  PAYMENT_EXCEEDS_REMAINING: 'PAYMENT_EXCEEDS_REMAINING',
  INVALID_METER_READING: 'INVALID_METER_READING',
  READING_ALREADY_INVOICED: 'READING_ALREADY_INVOICED',
  GATEWAY_SIGNATURE_INVALID: 'GATEWAY_SIGNATURE_INVALID',

  // Lỗi nhu yếu phẩm
  SUPPLY_ITEM_INACTIVE: 'SUPPLY_ITEM_INACTIVE',
  SUPPLY_ALREADY_INCLUDED: 'SUPPLY_ALREADY_INCLUDED',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',

  // Lỗi hệ thống nội bộ
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = ERROR_CODES;
