/**
 * Bảng mã lỗi chuẩn toàn hệ thống theo API.md §12.
 * Giúp Frontend định danh lỗi dạng máy đọc (machine-readable string).
 */

const ERROR_CODES = {
  // Lỗi xác thực và phân quyền
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  STUDENT_NOT_LINKED: 'STUDENT_NOT_LINKED',

  // Lỗi dữ liệu & validate
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Lỗi nghiệp vụ phòng & giường
  ROOM_CAPACITY_EXCEEDED: 'ROOM_CAPACITY_EXCEEDED',
  BED_NOT_AVAILABLE: 'BED_NOT_AVAILABLE',
  BED_OCCUPIED: 'BED_OCCUPIED',
  GENDER_MISMATCH: 'GENDER_MISMATCH',

  // Lỗi nghiệp vụ sinh viên & hợp đồng
  STUDENT_HAS_ACTIVE_CONTRACT: 'STUDENT_HAS_ACTIVE_CONTRACT',
  STUDENT_HAS_DEBT: 'STUDENT_HAS_DEBT',
  CONTRACT_NOT_ACTIVE: 'CONTRACT_NOT_ACTIVE',
  DUPLICATE_PENDING_REQUEST: 'DUPLICATE_PENDING_REQUEST',

  // Lỗi nghiệp vụ hóa đơn & thanh toán & điện nước
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_HAS_PAYMENT: 'INVOICE_HAS_PAYMENT',
  PAYMENT_EXCEEDS_REMAINING: 'PAYMENT_EXCEEDS_REMAINING',
  INVALID_METER_READING: 'INVALID_METER_READING',
  READING_ALREADY_INVOICED: 'READING_ALREADY_INVOICED',
  GATEWAY_SIGNATURE_INVALID: 'GATEWAY_SIGNATURE_INVALID',

  // Lỗi hệ thống nội bộ
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = ERROR_CODES;
